#!/bin/bash

# ------------------------------
# Locking down GRUB with a password
# ------------------------------

echo "[+] Securing GRUB..."

# Set password for GRUB (this will be generated by you)
read -sp "Enter your GRUB password: " grub_password
echo
echo "[+] Encrypting your password for GRUB..."

# Generate the password hash for GRUB
grub_hash=$(grub2-mkpasswd-pbkdf2 <<< $grub_password | grep -oP '(?<=hash is ).*')

# Update /etc/grub.d/40_custom with the encrypted password
echo "[+] Configuring GRUB..."

echo -e "set superusers=\"admin\"\npassword_pbkdf2 admin $grub_hash" >> /etc/grub.d/40_custom

# Regenerate GRUB config based on system (UEFI or BIOS)
if [ -d /sys/firmware/efi ]; then
  grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg  # UEFI systems
else
  grub2-mkconfig -o /boot/grub2/grub.cfg  # Legacy BIOS systems
fi

echo "[✔] GRUB is now secured with a password."


# ------------------------------
# Prevent root login via SSH
# ------------------------------

echo "[+] Disabling root SSH login..."

# Modify the SSH config to disable root login
sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config

# Restart SSH service to apply changes
systemctl restart sshd

echo "[✔] Root login via SSH has been disabled."


# ------------------------------
# Enable Full Disk Encryption (FDE) using LUKS
# ------------------------------

echo "[+] Encrypting your disk using LUKS..."

# WARNING: This will delete all data on the selected partition, ensure backups first!
# Let's assume the target partition is /dev/sda1 (change accordingly)

# Lock disk with LUKS encryption
cryptsetup luksFormat /dev/sda1
cryptsetup luksOpen /dev/sda1 encrypted_disk

# Create filesystem on the encrypted partition
mkfs.ext4 /dev/mapper/encrypted_disk

# Mount the encrypted partition
mount /dev/mapper/encrypted_disk /mnt

echo "[✔] Full disk encryption (FDE) has been enabled."


# ------------------------------
# Prevent physical root password reset (rd.break)
# ------------------------------

echo "[+] Ensuring rd.break is disabled..."

# Remove rd.break from GRUB config
grub_file="/etc/default/grub"
if grep -q "rd.break" $grub_file; then
  sed -i 's/rd.break//g' $grub_file
  grub2-mkconfig -o /boot/grub2/grub.cfg
  echo "[✔] rd.break has been removed from GRUB."
else
  echo "[✔] rd.break is already removed."
fi


# ------------------------------
# Final Steps: Reboot System
# ------------------------------

echo "[+] Security lockdown complete. Rebooting system..."
reboot
